default: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: marcelo
  password: 123456

development:
  <<: *defaults
  database: jumpstartrails_development

test: &test
  <<: *defaults
  database: jumpstartrails_test

production:
  <<: *defaults
  database: jumpstartrails_production

